### ISSUE TITLE
Make the application single-paged

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/kaiwa#100]
Currently there are multiple HTML pages, and all they brings is **pain**. We need to remove all of them and replace by single HTML file.

**Comment by unam3** [comment]
which pain in particular those five page bring to you?
$ find ./ -name *html|less
./public/error.html
./public/index.html
./public/layout.html
./public/login.html
./public/logout.html

**Comment by vitalyster** [comment]
all except index. And SERVERCONFIG also

**Comment by vitalyster** [comment]
https://github.com/ForNeVeR/kaiwa/issues/64

**Comment by ForNeVeR** [comment]
@unam3, the pain they brings is a bizzare patterns of parameter passing between them. These pages are passing parameters through local storage and that is neither good nor scalable at all. Also they're creating problems for build process (because we're forced to create distinct packs for some smaller scripts used only in those technical pages); error page have no access to the error information etc.

We need to clean this mess up and use reliable single-page solution. But I am ready to discuss alternate solutions for the issues mentioned, if you're up to propose something.

**Comment by ForNeVeR** [comment]
Superseded by #123.
