### ISSUE TITLE
A user gets highlighted when someone posts a link to MUC

### ISSUE THREAD

**Issue by rexim** [ForNeVeR/kaiwa#106]
A tkabber user with nickname "любитель криппи языков" gets highlighted when a kaiwa user with nickname "rexim" posts any HTTP URL link to a MUC codingteam@conference.jabber.ru.

Also, we need to get better reproduction instructions on that.

**Comment by rexim** [comment]
Also, we need to understand if it's a tkabber's problem or kaiwa's. Or both.

**Comment by ForNeVeR** [comment]
wat

**Comment by rexim** [comment]
That was my reaction too!

**Comment by ForNeVeR** [comment]
![image](https://cloud.githubusercontent.com/assets/92793/11814753/bf3c61e6-a372-11e5-9718-dd385c64e6fa.png)

**Comment by rexim** [comment]
wat

**Comment by vitalyster** [comment]
http://chatlogs.jabber.ru/support@conference.jabber.ru/2015/12/15.html#00:41:41.822509

**Comment by rexim** [comment]
@ForNeVeR @vitalyster so, what's your resolution on that? Invalid?

**Comment by vitalyster** [comment]
@rexim did you try suggested Tkabber plugin?

**Comment by rexim** [comment]
@vitalyster, of course not! I don't use Tkabber! Do I look like crazy or something?

Besides, it completely unclear from the logs what's the plugin (patch?) and how to get it. I'm sorry, but "somewhere in the logs" sounds like "fuck you".

**Comment by vitalyster** [comment]
I'm sorry but "I do not want to read exact 5 lines of log" sounds like "fuck you"

**Comment by ForNeVeR** [comment]
Here is it: http://chatlogs.jabber.ru/support@conference.jabber.ru/2015/09/22.html#17:44:31.206203

Currently we think that's tkabber bug. Please notify us and reopen on any further information.

**Comment by vitalyster** [comment]
The plugin - http://pastebin.com/Kvw7GKvT

**Comment by rexim** [comment]
@vitalyster, sorry, didn't actually mean that. And didn't want to offend you either. Just wanted to understand the situation and your link to that place in the log really confused me. And thanks for the plugin! :)

@ForNeVeR, thanks to you too! :)

**Comment by rexim** [comment]
@ForNeVeR @vitalyster also, I have one more request for you guys. Could please put the `Invalid` tag on this issue?

**Comment by ForNeVeR** [comment]
We haven't one and don't classify issues as such. Closed is enough. Goat approves.

**Comment by rexim** [comment]
Very well then. Thanks anyway! :)

**Comment by ForNeVeR** [comment]
I've also cleaned up this thread a bit.
