### ISSUE TITLE
Remember login info

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/kaiwa#11]
There should be an option to remember login/password in the browser so the user don't have to reenter them every time. It seems that there's some minimal support of local storage; we should check that.

**Comment by ForNeVeR** [comment]
While debugging #35 I've found that Kaiwa really stores the credentials, but (for security reasons, obviously?) it does not store the user password. Instead it saves login salt from the last time it has been logged in and trying to reuse the client and server keys it got from the previously salted password. Only those two keys and server salt are stored in the `localStorage`.

We'll need to investigate XMPP login process to make this work.

**Comment by ForNeVeR** [comment]
Well, it seems that it's really a problem with jabber.ru SCRAM algorithm: the server-generated salt is undeterministic currently. We'll have to implement some other mechanism to save the user credentials. If anything else fails - I'm ready to use browser internal password storage (not very great from the security point of view though).

**Comment by oxpa** [comment]
Please implement a checkbox like "a public PC", so that a user could definitely has his data removed from current PC.

**Comment by ForNeVeR** [comment]
That's a nice ideah.
