### ISSUE TITLE
Clicking on any avatar opens my settings

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/kaiwa#112]
Enter any conference, click any user avatar in the message view. You'll be redirected to Kaiwa settings. That's strange, maybe it'd be better to open full-screen avatar view in new browser tab or something like that.

**Comment by unam3** [comment]
I can't reproduce redirect in FF 42 and Chromium 46.

**Comment by ForNeVeR** [comment]
Agreed. I cannot reproduce either.
