### ISSUE TITLE
Message updates are working only for the first update

### ISSUE THREAD

**Issue by ChALkeR** [ForNeVeR/kaiwa#149]
To reproduce:
 1. Send «Hello». «Hello» is sent.
 2. Press up arrow, edit to «Hello, World». «Hello» is replaced with «Hello, World».
 2. Press up arrow, edit to «Good bye, World». Nothing happens visually, «Hello, World» is still shown.

Chat logs show all three messages separately, so the message actually got sent, just is not displayed by the client.

**Comment by ForNeVeR** [comment]
Looks like duplicate of #120.

**Comment by ChALkeR** [comment]
I swear I searched for those first =). I overlooked that one, though.
Yes, it's a duplicate, closing.
