### ISSUE TITLE
Stylus stylesheets out of sync with client.css

### ISSUE THREAD

**Issue by vitalyster** [ForNeVeR/kaiwa#19]
client.css was generated from *.styl, but someone edit them manually => I can't regenerate proper client.css

**Comment by ForNeVeR** [comment]
The only difference I see between the currently published version and the generated from the `client.styl` is the `min-width: auto;` line in the following context:

```
#calls button {
  min-width: auto;
  ...
```

Also there seems to be some problem with `rgba` generated everywhere. After we deal with that, we can enable generation of `client.css` from stylus.
