### ISSUE TITLE
@lukekarrys/jade-runtime no more available

### ISSUE THREAD

**Issue by Ansheos** [ForNeVeR/Kaiwa#212]
Hi,

Installing Kaiwa, it would seem that  is no more available on npm:

> ...
> 1897 error 404 Not Found
> 1897 error 404
> 1897 error 404 'lukekarrys/jade-runtime' is not in the npm registry.
> 1897 error 404 You should bug the author to publish it
> 1897 error 404 It was specified as a dependency of 'kaiwa.im'
> 1897 error 404
> 1897 error 404 Note that you can also install from a
> 1897 error 404 tarball, folder, or http url, or git url.
> 1898 error System Linux 3.12.56-guest-44-9e5f8dd-x86_64
> 1899 error command "/usr/bin/nodejs" "/usr/bin/npm" "install"
> 1900 error cwd /home/myuser/kaiwa
> 1901 error node -v v4.8.2
> 1902 error npm -v 1.4.21
> 1903 error code E404
> ...

Is there any workaround that I missed, or should Kaiwa use another runtime?

Thanks!

Regards.

**Comment by ForNeVeR** [comment]
Hello. It seems that `@lukekarrys/jade-runtime` is [still available](https://www.npmjs.com/package/@lukekarrys/jade-runtime) in npm. I cannot reproduce your issue.

Probably you're using some old version of npm (1.0?) that doesn't support [scoped packages](https://docs.npmjs.com/getting-started/scoped-packages)?

**Comment by Ansheos** [comment]
Thanks for you feedback.

It would seem you are right. Debian/Sid npm version is too old: 1.4.21

Way to go: install the latest npm version through the installer.
