### ISSUE TITLE
XEP 0363: HTTP File Upload support

### ISSUE THREAD

**Issue by patelvanita360** [ForNeVeR/Kaiwa#218]
i have setup kaiwa in local server, for backup i am using ejabberd, when i try to share image in chat its not working as well as call feature also not working

**Comment by patelvanita360** [comment]
Hello,

Is there any update on this issue ?

**Comment by vitalyster** [comment]
Do you have any logs in js console? (try to set `localStorage.debug = true` to get more verbose output)

**Comment by patelvanita360** [comment]
While i drag and drop any image in chrome, image open in browser instead of send it to user

**Comment by patelvanita360** [comment]
I am sending following request for image sharing in one to one chat :

client.use(shareMedia); // plugin created for share media
var message = {
from:me.jid,
id:client.nextId(),
to: 'upload.domainname',
type: 'get',
request: {
filename: file.name,
size: file.size
}
};
client.mediaPushService(message).then(function (err,data) {
if(err)console.log(err);
console.log('image upload');
}).catch(function (err) {
console.log('image not upload');
});

Response i am getting from xampp server(ejabberd i am using ) :
<<in iq xmlns='jabber:client' xml:lang='en' to='8000955974@uploaddomain/2497367150272585652773' from='upload.domain' type='result' id='19b5807f-0b10-46a3-b037-e1c9f46668c0
slot xmlns='urn:xmpp:http:upload:0'
get url='https://uploaddomain/975fb8db938152f973ef26ba56681228d5296634/WgaDXKEx67McKPPnGHMIOGzssRzkalozdK1cRHMQ/boy.png'/
put url='https://uploaddomain/975fb8db938152f973ef26ba56681228d5296634/WgaDXKEx67McKPPnGHMIOGzssRzkalozdK1cRHMQ/boy.png'/
slot
/iq

I could not find image on given slot.

Note : i have removed response xaml "<" and " >" tags because it was not printing here

**Comment by patelvanita360** [comment]
Hello,

Is there any update on this issue ?

**Comment by ForNeVeR** [comment]
Honestly I don't understand what's going on. Why are you showing us the JS code? Is it Kaiwa code? Are you somehow patching it? I wasn't able to find the code you're referencing in our code base. What is it exactly?

**Comment by vitalyster** [comment]
@patelvanita360 if you are trying to implement http upload support in Kaiwa, then you should follow http upload XEP. From my quick view - you are requesting upload slot and receive urls for GET and PUT, now you need to PUT image first, and then it will be available on GET url

**Comment by patelvanita360** [comment]
Can you please tel me how to put image on given slot pur URL?

**Comment by vitalyster** [comment]
Just use Fetch API

**Comment by patelvanita360** [comment]
Can you please share any reference?

**Comment by vitalyster** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API

**Comment by patelvanita360** [comment]
Can you please check following : 
I got error while use fetch API 
Fetch API cannot load 'PUT URL'. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'LOCAL SERVER' is therefore not allowed access. The response had HTTP status code 405. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by vitalyster** [comment]
You must enable CORS header on HTTP URLs on your server side to make HTTP requests from browser applications

**Comment by patelvanita360** [comment]
i have enabled cors header and i am using POST method to upload data on given put URL
its display error like 
405 (Method Not Allowed)

**Comment by vitalyster** [comment]
Sure, because it allows only HTTP PUT method

**Comment by patelvanita360** [comment]
But when i am using PUT methos its display
TypeError: Failed to execute 'fetch' on 'Window': 'PUT' is unsupported in no-cors mode
I am uploading image from local server

**Comment by vitalyster** [comment]
As your server supports CORS, you should NOT add no-cors parameter

**Comment by patelvanita360** [comment]
Ok Thank you so much for your valuable time now it seems like working ....

One more question i have that how can I fetch PUT URL from ejabberd response ?

**I am getting log like this :** 
<iq xmlns='jabber:client' xml:lang='en' to='8000955972@domain/176928046368959318551353' from='upload.domain' type='result' id='3cbc09c7-aeae-45be-9f6f-ae75531a1bd5'><slot xmlns='urn:xmpp:http:upload:0'><get url='https://domain:5444/bbe52498d96b7edc6d45cab8575fbf43f4604754/0BZM44WOowpu7o4HieQYxzdH43QafizJL7UlP6PE/girl.png'/><put url='https://domain:5444/bbe52498d96b7edc6d45cab8575fbf43f4604754/0BZM44WOowpu7o4HieQYxzdH43QafizJL7UlP6PE/girl.png'/></slot></iq>

**Comment by vitalyster** [comment]
Not sure I'm understand you question. What is "make it dynamic"?

**Comment by patelvanita360** [comment]
I want to upload image data on PUT url given by requested slot. For now i just put static put url in fetch api method, but now i want to get that PUT url real time on response given by requested slot.

**Comment by patelvanita360** [comment]
Yes I got it but still you don't understand my query. Let me raise query from your last replay so i will get my ans
var result = jxt.parse("HOW CAN I GET THIS DATA");

**Comment by vitalyster** [comment]
`client.sendIQ` have second callback parameter `(error, response)` where response is the reply to your slot request you passed as first parameter

**Comment by patelvanita360** [comment]
I have tried a lot in a different different way but Not getting luck. not getting a response which I want, can i mail you that file?

**Comment by vitalyster** [comment]
```
client.mediaPushService = function (message) {
return client.sendIq(message);
};
```

I did not see you are using sendIq callback

**Comment by patelvanita360** [comment]
i had use like this , but its not working 

client.mediaPushService = function (message) {
return client.sendIq(message,function(error,response){
   console.log(response);
});

**Comment by vitalyster** [comment]
what is in log?

**Comment by vitalyster** [comment]
And I didn't see slot urls definition in your shareMedia stanza extension

**Comment by patelvanita360** [comment]
I had put that code given by as it is but its stop the compilation so I
removed it

**Comment by patelvanita360** [comment]
i got kaiwa complation error  while i integrate code given by you 

[/backup/html/node_modules/jxt-xmpp]
 @ ./src/js/helpers/shareMedia.js 7:12-31
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kaiwa.im@1.1.0 compile: `gulp compile`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the kaiwa.im@1.1.0 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by patelvanita360** [comment]
**shareMedia.js**

`"use strict";

module.exports = function (client, stanzas) {
    var types = stanzas.utils;
    let jxt = require('jxt').createRegistry();
    jxt.use(require('jxt-xmpp-types'));
    jxt.use(require('jxt-xmpp'));
    let helpers = jxt.utils;

    let UPLOAD_NS = 'urn:xmpp:http:upload:0';   

    var shareMedia = stanzas.define({
        name: 'request',
        element: 'request',
        namespace: 'urn:xmpp:http:upload:0',
        fields: {           
           size: types.attribute('size'),
            filename: types.attribute('filename')
           
            
        }      
    });
    stanzas.withIq(function (Iq) {
        stanzas.extend(Iq, shareMedia);
    });

    var uploadMediaData = stanzas.define({
        name: 'uploadMediaData',
        namespace: 'urn:xmpp:push:0',
        element: 'request',
        fields: {
            data: types.text()
        }
    });    

    stanzas.withIq(function (Iq) {
        stanzas.extend(Iq, uploadMediaData);
    });

    client.uploadMedia = function (message) {        
        return client.sendIq(message);
    };

    let UploadSlot = jxt.define({
        name: 'uploadSlot',
        namespace: UPLOAD_NS,
        element: 'slot',
        fields: {
            get: helpers.subAttribute(UPLOAD_NS, 'get', 'url'),
            put: helpers.subAttribute(UPLOAD_NS, 'put', 'url')
        }
    });

    jxt.extendIQ(UploadSlot);

    client.mediaPushService = function (message) {
        client.sendIq(message,function(error,response){
            console.log("jxt parsing :" + jxt.parse(response));
            var result = jxt.parse("<iq xmlns='jabber:client' xml:lang='en' to='8000955974@upload.domain/2497367150272585652773' from='upload.domain' type='result' id='19b5807f-0b10-46a3-b037-e1c9f46668c0'><slot xmlns='urn:xmpp:http:upload:0'><get url='https://domain:5444/975fb8db938152f973ef26ba56681228d5296634/WgaDXKEx67McKPPnGHMIOGzssRzkalozdK1cRHMQ/boy.png'/><put url='https://domain:5444/975fb8db938152f973ef26ba56681228d5296634/WgaDXKEx67McKPPnGHMIOGzssRzkalozdK1cRHMQ/boy.png'/></slot></iq>");
            console.log("PUT URL is " + result.uploadSlot.put);            
        });
    }
    
};`

**chat.js** 

`   handleMediaClick: function(e){
        e.preventDefault();
        var self = this;
        console.log(this.model.topResource);
        var file;
        if (e.dataTransfer) {
            file = e.dataTransfer.files[0];
        } else if (e.target.files) {
            file = e.target.files[0];
        } else {
            return;
        }

        if (file.type.match('image.*')) {
            var downloadURL = URL.createObjectURL(file);
            console.log('Offering:', file.name, file.size, file.type, file.lastModifiedDate,  downloadURL);
            
            var fileTracker = new FileReader();
          
            fileTracker.onload = function () {
            console.log('file', file.name, file.size, file.type, file.lastModifiedDate);
            var data =  this.result; 
            var resampler = new Resample(data, 80, 80, function (data) {
            var b64Data = data.split(',')[1];
            var id = crypto.createHash('sha1').update(atob(b64Data)).digest('hex');   
            client.use(shareMedia);
            
            var message = {
                    from:me.jid,
                    id:client.nextId(),
                    to: 'upload.domain',          
                    type: 'get',
                    request: {
                        filename: file.name,
                        size: file.size                       
                    }
                };
            client.mediaPushService(message).then(function (result) {
                 console.log("PUT URL is " + result);

                if (!('fetch' in window)) {
                  console.log('Fetch API not found, try including the polyfill');
                  return;
                }

                let header = new Headers({
                    'Access-Control-Allow-Origin': '*',
                    'Access-Control-Allow-Methods': 'GET, POST, PUT,OPTIONS',
                    'Access-Control-Allow-Headers': 'Content-Type',
                    'Access-Control-Max-Age': '86400',
                    'Content-Type': 'multipart/form-data'
                });

                fetch('https://domain:5444/bbe52498d96b7edc6d45cab8575fbf43f4604754/Gyv1fZadeQWnmzLVOgFamnKkDvphH5hVENOLrkH5/app-icon.png', {
                  method: 'PUT',
                   mode: 'cors',
                   header : header,
                   body: id
                })
                if(err)console.log(err); 
                
                client.sendMessage({
                  id: client.nextId(), 
                  type:'chat',
                  to: self.model.topResource,
                  body:b64Data
                });
                console.log('Could enable push notifications');
            }).catch(function (err) {
                console.log('Could not enable push notifications');
            });

            });
        }
         fileTracker.readAsDataURL(file);
        }        
    },    `

**Comment by vitalyster** [comment]
1) no need to import jxt, as required JXT object is passed to module as `stanzas`
2) your `mediaPushService` is not a Promise, so you can not use `then` there, that is what console say to you

**Comment by vitalyster** [comment]
> 413 (Request Entity Too Large)

That is your server configuration

**Comment by patelvanita360** [comment]
i have set headers on server , can you suggest me which other configuration need to change ?

**Comment by vitalyster** [comment]
Entity too large means your upload limit too low

**Comment by patelvanita360** [comment]
that solved but still getting this

```
Fetch API cannot load https://domain:5444/975fb8db938152f973ef26ba56681228d5296634/kwjCxd9nhAk5KILEavBhR1EcvsCQ57uNixE07qQO/app-icon.png. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://192.168.1.28:8000' is therefore not allowed access. The response had HTTP status code 413. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
:8000/#chat/8000955972%40domain:1 Uncaught (in promise) TypeError: Failed to fetch
```

**Comment by vitalyster** [comment]
Error message clearly states it does not found cors header on server

**Comment by patelvanita360** [comment]
My server configuration : 

```
 mod_http_upload:
    docroot: "@HOME@/upload"
    put_url: "https://@HOST@:5444"
    max_size: 5000000    #5MB
    custom_headers:
      "Access-Control-Allow-Origin": "*"
      "Access-Control-Allow-Methods": "GET, POST, PUT, OPTIONS, DELETE"
      "Access-Control-Allow-Headers": "Content-Type, Origin, X-Requested-With"
    thumbnail: false # otherwise needs ejabberd to be compiled with libgd support
  mod_http_upload_quota:
    max_days: 30
  mod_last: {}

```

**Comment by vitalyster** [comment]
I did not see any reference to custom_headers in [mod_http_upload](https://hg.prosody.im/prosody-modules/file/tip/mod_http_upload/mod_http_upload.lua) source code, so I think you need to fix that module first

**Comment by patelvanita360** [comment]
https://docs.ejabberd.im/admin/configuration/#mod-http-upload 
i have setup custom headers from here 
is there any reference link to fix this ?

**Comment by vitalyster** [comment]
I think you should configure your PUT url as `put_url: "https://@HOST@/upload:5444"` as module maybe adds headers only to `docroot` urls

**Comment by vitalyster** [comment]
You also miss `host` configuration which is `upload.@HOST@` by default, and your PUT url may should match host url to set custom_headers

**Comment by patelvanita360** [comment]
still got same error , is there any other method to upload image data ?

**Comment by vitalyster** [comment]
That is your server misconfiguration, ask ejabberd support on that

**Comment by vitalyster** [comment]
trying to ping @weiss :)

**Comment by weiss** [comment]
> The response had HTTP status code 413.

`mod_http_upload` will return this code if the size of the file uploaded with the PUT request doesn't match the size specified in the PUT request.  ejabberd will write an `[info]` message to your ejabberd.log in that case, please always check the logs when running into trouble.

**Comment by vitalyster** [comment]
@weiss I think he set upload limits and now only CORS headers are not configured

**Comment by weiss** [comment]
> I think he set upload limits and now only CORS headers are not configured

But the 413 status is mentioned in [the last error message he quoted][1].  The CORS headers are only included in the success case.

[1]: https://github.com/ForNeVeR/Kaiwa/issues/218#issuecomment-386978483

**Comment by patelvanita360** [comment]
@weiss yes, i resolved this limit issue, CORD issue is there 
Now i am getting following error: 
> Fetch API cannot load https://domain:5444/975fb8db938152f973ef26ba56681228d5296634/ACiyS38WrF3EzxyMdUz7W0H9Y9i9yhymivFY42Jm/app-icon__1_.png. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://192.168.1.28:8000' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
> :8000/#chat/8000955972%40domain:1 Uncaught (in promise) TypeError: Failed to fetch

**Comment by vitalyster** [comment]
>  Response to preflight request 
Preflight request is OPTIONS request, need to check is it really handled my mod_http_upload

**Comment by weiss** [comment]
> Preflight request is OPTIONS request, need to check is it really handled my mod_http_upload

Yes `mod_http_upload` responds to `OPTIONS` requests.

**Comment by patelvanita360** [comment]
listener

>  port: 5444
>     ip: "::"
>     module: ejabberd_http
>     request_handlers:
>       "": mod_http_upload
>     tls: true
>     certfile: 'CERTFILE'
>     protocol_options: 'TLS_OPTIONS'
>     http_bind: true



mod_http_upload:

>     docroot: "@HOME@/upload"
>     put_url: "https://@HOST@:5444"
>     max_size: 5000000    #5MB
>     custom_headers:
>       "Access-Control-Allow-Origin": "*"
>       "Access-Control-Allow-Methods": "GET, POST, PUT, OPTIONS, DELETE"
>       "Access-Control-Allow-Headers": "Content-Type, Origin, X-Requested-With"
>     thumbnail: false # otherwise needs ejabberd to be compiled with libgd support
> mod_http_upload_quota:
>     max_days: 30

**Comment by weiss** [comment]
Could you open an `ejabberdctl debug` shell and copy the output of the following call?

    gen_mod:get_module_opt(<<"example.com">>, mod_http_upload, custom_headers).

Replace `example.com` with your domain, don't forget the trailing `.`, and press `Ctrl`+`C` twice when you're done.

**Comment by patelvanita360** [comment]
ejabberd@db01)1> gen_mod:get_module_opt(<<"domain.com">>, mod_http_upload, custom_headers). 
[{<<"Access-Control-Allow-Origin">>,<<"*">>},
 {<<"Access-Control-Allow-Methods">>,
  <<"GET, POST, PUT, OPTIONS, DELETE">>},
 {<<"Access-Control-Allow-Headers">>,
  <<"Content-Type, Origin, X-Requested-With">>}]

**Comment by weiss** [comment]
Looks good, except that you should remove `POST` and `DELETE` from the methods list, and add `HEAD`.

Your [last error message][1] doesn't mention the request type nor the response code.  Maybe the request failed for some reason and the CORS headers are missing from the error response.  There's nothing in your `ejabberd.log` regarding this request?

You could create a file in your upload directory and check whether the CORS headers are included with a GET request using another client, e.g.:

```sh
    mkdir -p ~ejabberd/upload/foo/bar && echo hi > ~ejabberd/upload/foo/bar/test.txt
    curl -i https://example.com:5444/foo/bar/text.txt
    rm -r ~ejabberd/upload/foo
```

Replace `ejabberd` with the name of the user running ejabberd (though often this *is* the name), and of course `example.com` with your domain name.

[1]: https://github.com/ForNeVeR/Kaiwa/issues/218#issuecomment-387039527

**Comment by vitalyster** [comment]
@weiss shouldn't mod_http_upload automatically set correct CORS headers without any `custom_headers` directives?

**Comment by weiss** [comment]
@vitalyster, not sure you want `Access-Control-Allow-Origin: *` in all environments, but maybe.

**Comment by vitalyster** [comment]
@weiss prosody's module have `cross_domain` option accepts 'true' or list of domains

**Comment by patelvanita360** [comment]
@weiss 
Here you can see ejabberd log. https://pastebin.com/DADZWZrB

I have doubt in this line: 
2018-05-07 08:49:52.008 [info] <0.16110.1>@mod_http_upload:process:409 Rejecting file from ::ffff:123.567.8.321 for domain: Unexpected size (10182)

I have already defined "max_size: 5000000    #5MB" Not sure which size it's taking there.

**Comment by weiss** [comment]
>  Rejecting file from ::ffff:123.567.8.321 for domain: Unexpected size (10182)

This is the case where the module returns a status of 413.  As I told you in my [very first response][1], this is not about hitting a limit; the problem is that the size you're specifying in the [slot request][2] doesn't match the size of the data you're submitting with the PUT request (the latter is 10182 bytes).

Please always check the logs when running into trouble.

[1]: https://github.com/ForNeVeR/Kaiwa/issues/218#issuecomment-387038488
[2]: https://xmpp.org/extensions/xep-0363.html#request

**Comment by vitalyster** [comment]
Show latest sending code, please

**Comment by patelvanita360** [comment]
https://pastebin.com/YdZhQK07 
i am doing this process for image data format

**Comment by vitalyster** [comment]
how did you read file and create b64data variable? If it is a base64 encoded - it's wrong, you need to send plain octet stream

**Comment by patelvanita360** [comment]
https://pastebin.com/TwXTVPga

**Comment by patelvanita360** [comment]
data variable contain data like "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgA......."

**Comment by vitalyster** [comment]
OK, so you need to decode it first and use correct decoded size in slot request and decoded data in PUT request

**Comment by patelvanita360** [comment]
@vitalyster , @weiss 
Finally its working now. Thank you so much again for your quick support. :)

**Comment by vitalyster** [comment]
will you contribute you work back to Kaiwa, or we spend our time for free? :)

**Comment by patelvanita360** [comment]
:) yes sure. will contribute it

**Comment by patelvanita360** [comment]
@vitalyster  , merge request sent, please check and accept it. :)

**Comment by patelvanita360** [comment]
Can you please tell me where can I call sharemedia plugin globally ?
Currently i am calling plugin on media change event.

**Comment by vitalyster** [comment]
Not sure I am understand the question, please elaborate?

**Comment by vitalyster** [comment]
If I understand correctly, you want to enable plugin, it should be done there: https://github.com/ForNeVeR/Kaiwa/blob/master/src/js/app.ts#L110

**Comment by patelvanita360** [comment]
Yes exactly but when i initialize in app.ts file its not working ...

**Comment by vitalyster** [comment]
Error messages?

**Comment by patelvanita360** [comment]
> sharemedia not defined

**Comment by vitalyster** [comment]
`shareMedia` is the variable where your plugin loaded, you should move `var shareMedia = require('../helpers/shareMedia');` line too. Note, you need to change path to be relative to app.ts

**Comment by patelvanita360** [comment]
now its working , thank you . :)

**Comment by vitalyster** [comment]
can you update your pull request?

**Comment by vitalyster** [comment]
Thanks! let's discuss it in the PR itself

**Comment by stevenroose** [comment]
Wait, was this implemented after all?

**Comment by vitalyster** [comment]
@stevenroose work in progress [there]( https://github.com/ForNeVeR/Kaiwa/pull/223)

**Comment by stevenroose** [comment]
@vitalyster is there maybe a MUC where you guys hang out? :)

**Comment by patelvanita360** [comment]
@vitalyster I have raise one query , can you please update me [there](https://github.com/ForNeVeR/Kaiwa/pull/223)  so i can work on it further.
