### ISSUE TITLE
xmpp-socket

### ISSUE THREAD

**Issue by albjeremias** [ForNeVeR/kaiwa#227]
What is an xmpp-socket? How do I set it up? :)
thanks.

**Comment by vitalyster** [comment]
context please?

**Comment by albjeremias** [comment]
sorry you are right.. https://github.com/ForNeVeR/Kaiwa/blob/master/dev_config.example.json#L15
I have this link to the XMPP server i want to test:
https://disroot.org:5281/http-bind

**Comment by vitalyster** [comment]
you need to install [`mod_websocket`](https://prosody.im/doc/modules/mod_websocket.html) to be able connect with kaiwa, when mod_websocket will be loaded - it should be available at https://disroot.org:5281/xmpp-websocket

**Comment by albjeremias** [comment]
hmm ok... i see.. should be interesting in another project to try to setup the whole xmpp server up using docker (including the LDAP, prosody, and this module!... ) 
 - also a mental note dont forget to add it to the README! :)

**Comment by ForNeVeR** [comment]
I believe you should be able to use http-bind with stanza.io like this: https://github.com/legastero/stanza.io/issues/134#issuecomment-192980511

Check the following code in Kaiwa: https://github.com/ForNeVeR/Kaiwa/blob/a86d4080994d49e5e6195188e7fda230ba66d437/src/resources/js/login.js#L18-L27

It tries to determine whether to use bosh or websocket, and should already work with your link.
