### ISSUE TITLE
Display One to One chat history issue 

### ISSUE THREAD

**Issue by patelvanita360** [ForNeVeR/kaiwa#230]
Hello @vitalyster  , How can i display one to one chat history.
mod_mam is enable on ejabberd server.

**Comment by patelvanita360** [comment]
@vitalyster  can you please give me update  on my last query ?

**Comment by vitalyster** [comment]
mam is automatically queried on start for all contacts and result is stored in chats. Again, you can check the XML log to verify that

**Comment by patelvanita360** [comment]
yes @vitalyster , i am getting chat history only localStorage.debug = true is set in console, otherwise not getting history. How can i show it without console localStorage.debug = true ?

**Comment by vitalyster** [comment]
That’s very strange, do you have some errors in JavaScript console? 

--

**Comment by patelvanita360** [comment]
No not any error , I test many times and i notice that there is no concern with console to loading history,
But Some time history loading and some time not loading.

**Comment by patelvanita360** [comment]
@vitalyster , Do you any reason behind it ?

**Comment by vitalyster** [comment]
Works for me, I can not reproduce so I can't help

**Comment by patelvanita360** [comment]
@vitalyster , I have installed fresh kaiwa and its working for me also, may me because of customization this problem is happens to me. I will look it. 

If you want to see this issue then please check once with `npm run compile` , i am facing this problem in default source also. Any ways its working with `npm start` .

Thank you @vitalyster  for your valuable time and instant support. 
Thanks again.
