### ISSUE TITLE
Node module integration Not working in Kaiwa

### ISSUE THREAD

**Issue by patelvanita360** [ForNeVeR/kaiwa#231]
Hello All, 

I am doing integration of following Node Module in Kaiwa for send emoji in chat.
https://www.npmjs.com/package/emojionearea
I follow below steps
1. npm install emojionearea  --save
2. create custom.js file 
3. Add following code in custom.js fil

  
        

> $(document).ready(function() {
>             $(".emojionearea").emojioneArea();
>        });

4. Add class _emojionearea_ to chat input textarea in chat.jade
5. Add 
`
var emoji = require('node-emoji');
var emojipicker = require('emojionearea'); 
require('custom.js');
` 
in chat.js

But not getting any result front side, can you please check where i am doing mistake ?
Not getting any error in console.

**Comment by vitalyster** [comment]
I think the chat input area is not ready yet on document.ready event. Try to call your jquery plugin in render() function in `pages/chat.js`

**Comment by patelvanita360** [comment]
tried. Still not working 

> render: function () {
>         if (this.rendered) return this;
>         var self = this;
>         this.rendered = true;
>         this.renderAndBind();
>         var emoji = require('node-emoji');
>         var emojipicker = require('emojionearea');  
>         require('custom.js');

**Comment by vitalyster** [comment]
this works for me - https://pastebin.com/xM9tiMW2

**Comment by vitalyster** [comment]
while your are trying now to use it AFTER rendering :)

**Comment by patelvanita360** [comment]
okay let me try

**Comment by patelvanita360** [comment]
Thank You. Working Now :) :)
