### ISSUE TITLE
How to do SSL integration ?

### ISSUE THREAD

**Issue by patelvanita360** [ForNeVeR/kaiwa#235]
Hello , Can anyone tel me how can I integrate  SSL in kaiwa . I want to run chat portal on HTTPS port. Please help me.

**Comment by vitalyster** [comment]
Just point your nginx or apache secured virtual host to Kaiwa's `public` directory

**Comment by patelvanita360** [comment]
And in kaiwa dev_config.json also same port will use which we use in virtual host file?

And how can I run kaiwa chat without start npm service ?

**Comment by vitalyster** [comment]
`npm run compile` produces `public` directory with all static files, no need to start npm service in production.
Yes, address and port in config should match apache/nginx virtualhost settings
