### ISSUE TITLE
How to allow cross domain ?

### ISSUE THREAD

**Issue by patelvanita360** [ForNeVeR/kaiwa#236]
Hello @vitalyster ,

Can you please help to solve following error

I am accessing kaiwa in iframe and getting username and password from parent content but it giving me following error. 

`Uncaught DOMException: Blocked a frame with origin from accessing a cross-origin frame.`

Where can I allow origin ?

**Comment by vitalyster** [comment]
You are doing something totally wrong. What do you want to achieve?

**Comment by patelvanita360** [comment]
I just want to enable CORS in header.

**Comment by ForNeVeR** [comment]
We don't recommend to use the embedded development server (the one you get using `npm start`) in production. You better get a real server (e.g. nginx) and set it up as you want.

If you still insist on using Express, then please read Expess documentation on CORS. This is not a Kaiwa issue.
