### ISSUE TITLE
header.css file

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/kaiwa#25]
I cannot get whether this file was compiled with stylus or not; it is also unknown whether it is used by current code or not. We should investigate.

**Comment by vitalyster** [comment]
Duplicate of #19

**Comment by ForNeVeR** [comment]
No it is not. #19 is all about `client.css`; this is about `header.css`.

**Comment by vitalyster** [comment]
there is a `header.styl` which included from `client.styl` and stylus successfully compiles `client.css` and it matches repo version
