### ISSUE TITLE
strange 'Connection' window on kaiwa login

### ISSUE THREAD

**Issue by oxpa** [ForNeVeR/kaiwa#35]
sometimes kaiwa freezes before login screen with 'connecting...' message.
The last request is 'https://jabber.ru/ws' which is successfull and returns '101'.

After a minute or so kaiwa redirects to login page.
If you login, you see the same 'connecting..' page for a second or so and get into the client.

This is reproduced with 100% success rate: at a login page navigate back to the root page and you will see 'connecting...' again. While page refresh and 'cancel' button help skipping the timeout they don't solve the issue itself.

**Comment by ForNeVeR** [comment]
It seems to be an erroneous data in the local storage.
