### ISSUE TITLE
Roster sorting 

### ISSUE THREAD

**Issue by oxpa** [ForNeVeR/kaiwa#39]
There are three statuses in the roster: green, orange and red. While orange status is sorted to the bottom, the red one (afaik, dnd) are alphabetically sorted along with "online" users.
 I believe, status sorting is confusing, cause a user have to look through the whole list searching for a contact he needs
Please, remove status sorting at all (leave only alphabetical).

**Comment by ForNeVeR** [comment]
Maybe it's the consequence of #17.

**Comment by hi-q** [comment]
Ability of status/alphabet sorting to be provided

**Comment by ForNeVeR** [comment]
Finally we decided to force alphabet sorting and add a status filtering feature. So, sorting was implemented with f3ecf49068adf853c5827f103349bbcaf2ba98a1, I am closing this.
