### ISSUE TITLE
Host base setting

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/kaiwa#46]
Kaiwa should be able to run in any virtual host (e.g. `localhost/kaiwa`, not only `localhost/`).

**Comment by vitalyster** [comment]
Cannot GET /chat/

**Comment by ForNeVeR** [comment]
Why?

**Comment by ForNeVeR** [comment]
I think that's the problem with your server setup.

**Comment by vitalyster** [comment]
Fixed
