### ISSUE TITLE
Use libraries from npm

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/kaiwa#47]
Such libraries as `IndexedDBShim`, `jquery*`, `resampler`, `sugar`, `zepto` should definitely be removed from the repository and we should instead reference the corresponding npm packages. I am not sure about `libraries/ui.js` - it have no clues to real library name and where could we got it. Moreover, it seems that it was generated from something.

The same about library CSS.

**Comment by vitalyster** [comment]
fixed in 2df0827eaf
