### ISSUE TITLE
Decide what to do with the Docker stuff

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/kaiwa#5]
Currently there's a Docker image build instruction with the code. I had no luck with running the image built from this; we have to decide whether we need that or not. And, for sure, delete it if it is not supported.

**Comment by oxpa** [comment]
We should remove it for now and use debian packages. It is highly desired to remove node.js from final distribution: in browser app and ejabberd should be sufficient to run a client.

**Comment by ForNeVeR** [comment]
Okay, I've dropped the tight dependency on express and node.js, and I'm deleting the Docker stuff. If you want to contribute Debian packages or anything such that - you're welcome. Sadly, I cannot contribute or support them by myself for the reason you know.
