### ISSUE TITLE
Typescript integration

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/kaiwa#6]
All the new code should be fully type checked by the TypeScript compiler. There are too many problems due to JavaScript's dynamic nature; it's time to overcome this. We'll need to find a way to integrate TypeScript compiler into Kaiwa build and serving process.

**Comment by ForNeVeR** [comment]
Initial TypeScript support done in 82a35f55b65b0e621c4c408863869693237ffe5a.

**Comment by jt3k** [comment]
Просто по-человечески писать код нужно. И проблем с динамичностью языка не возникнет.

Долгое время динамическая типизация являлась плюсом а не минусом. А теперь мы снова возвращаемся к тому откуда пришли.

**Comment by ForNeVeR** [comment]
Ну, вы-то, может, и возвращаетесь туда, откуда пришли, а мы идём туда, где ещё не бывали: в новый мир генериков, зависимых и структурных типов, ну и всякого такого.

Машина должна работать вместо человека и проверять корректность программы, а не наоборот.
