### ISSUE TITLE
Replace SERVER_CONFIG with require('./dev_config')

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/kaiwa#64]
That configuration shouldn't stay in the separate file, it can be used directly.

**Comment by vitalyster** [comment]
I think we can drop dev_ prefix

**Comment by ForNeVeR** [comment]
Yeah, that's a nice idea.

**Comment by ForNeVeR** [comment]
We don't need it anymore; was replaced by `KAIWA_CONFIG` injected by `webpack.DefinePlugin`.
