### ISSUE TITLE
Node version requirement

### ISSUE THREAD

**Issue by bangarharshit** [ForNeVeR/kaiwa#75]
Hi, I am using kaiwa with ejabberd. I am unable to resolve dependency for kaiwa (The dependency is resolved for digicoop kaiwa). Is there a  node version and npm requirement.

Thanks,
Harshit

**Comment by vitalyster** [comment]
what is the error in `npm install` output?

**Comment by bangarharshit** [comment]
Adding logs:


npm http 404 https://registry.npmjs.org/lukekarrys/jade-runtime
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/share/npm/lib/cache.js:687:35)
npm ERR!     at /usr/share/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.16.0-30-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/harshit/Downloads/kaiwa
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type non_object_property_load


make: Entering directory `/home/harshit/Downloads/kaiwa/node_modules/jxt/node_modules/ltx/node_modules/node-expat/build'
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlparse.o
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmltok.o
../deps/libexpat/lib/xmltok.c:471:1: warning: missing initializer for field ‘isName2’ of ‘const struct normal_encoding’ [-Wmissing-field-initializers]
 };
 ^
../deps/libexpat/lib/xmltok.c:186:21: note: ‘isName2’ declared here
   int (PTRFASTCALL *isName2)(const ENCODING *, const char *);
                     ^
../deps/libexpat/lib/xmltok.c:484:1: warning: missing initializer for field ‘isName2’ of ‘const struct normal_encoding’ [-Wmissing-field-initializers]
 };
 ^
../deps/libexpat/lib/xmltok.c:186:21: note: ‘isName2’ declared here
   int (PTRFASTCALL *isName2)(const ENCODING *, const char *);
                     ^
../deps/libexpat/lib/xmltok.c:504:1: warning: missing initializer for field ‘isName2’ of ‘const struct normal_encoding’ [-Wmissing-field-initializers]
 };
 ^
../deps/libexpat/lib/xmltok.c:186:21: note: ‘isName2’ declared here
   int (PTRFASTCALL *isName2)(const ENCODING *, const char *);
                     ^
../deps/libexpat/lib/xmltok.c:517:1: warning: missing initializer for field ‘isName2’ of ‘const struct normal_encoding’ [-Wmissing-field-initializers]
 };
 ^
../deps/libexpat/lib/xmltok.c:186:21: note: ‘isName2’ declared here
   int (PTRFASTCALL *isName2)(const ENCODING *, const char *);
                     ^
../deps/libexpat/lib/xmltok.c:730:1: warning: missing initializer for field ‘isName2’ of ‘const struct normal_encoding’ [-Wmissing-field-initializers]
 };
 ^
../deps/libexpat/lib/xmltok.c:186:21: note: ‘isName2’ declared here
   int (PTRFASTCALL *isName2)(const ENCODING *, const char *);
                     ^
../deps/libexpat/lib/xmltok.c:749:1: warning: missing initializer for field ‘isName2’ of ‘const struct normal_encoding’ [-Wmissing-field-initializers]
 };
 ^
../deps/libexpat/lib/xmltok.c:186:21: note: ‘isName2’ declared here
   int (PTRFASTCALL *isName2)(const ENCODING *, const char *);
                     ^
../deps/libexpat/lib/xmltok.c:762:1: warning: missing initializer for field ‘isName2’ of ‘const struct normal_encoding’ [-Wmissing-field-initializers]
 };
 ^
../deps/libexpat/lib/xmltok.c:186:21: note: ‘isName2’ declared here
   int (PTRFASTCALL *isName2)(const ENCODING *, const char *);
                     ^
../deps/libexpat/lib/xmltok.c:775:1: warning: missing initializer for field ‘isName2’ of ‘const struct normal_encoding’ [-Wmissing-field-initializers]
 };
 ^
../deps/libexpat/lib/xmltok.c:186:21: note: ‘isName2’ declared here
   int (PTRFASTCALL *isName2)(const ENCODING *, const char *);
                     ^
../deps/libexpat/lib/xmltok.c:871:1: warning: missing initializer for field ‘isName2’ of ‘const struct normal_encoding’ [-Wmissing-field-initializers]
 };
 ^
../deps/libexpat/lib/xmltok.c:186:21: note: ‘isName2’ declared here
   int (PTRFASTCALL *isName2)(const ENCODING *, const char *);
                     ^
../deps/libexpat/lib/xmltok.c:890:1: warning: missing initializer for field ‘isName2’ of ‘const struct normal_encoding’ [-Wmissing-field-initializers]
 };
 ^
../deps/libexpat/lib/xmltok.c:186:21: note: ‘isName2’ declared here
   int (PTRFASTCALL *isName2)(const ENCODING *, const char *);
                     ^
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlrole.o
  AR(target) Release/obj.target/deps/libexpat/libexpat.a
  COPY Release/libexpat.a
  CXX(target) Release/obj.target/node_expat/node-expat.o
  SOLINK_MODULE(target) Release/obj.target/node_expat.node
  SOLINK_MODULE(target) Release/obj.target/node_expat.node: Finished
  COPY Release/node_expat.node
make: Leaving directory `/home/harshit/Downloads/kaiwa/node_modules/jxt/node_modules/ltx/node_modules/node-expat/build'
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/harshit/Downloads/kaiwa/npm-debug.log
npm ERR! not ok code 0

**Comment by vitalyster** [comment]
try node 0.12.x or 4.x

**Comment by bangarharshit** [comment]
Thanks working.
