### ISSUE TITLE
Problem with templates.js

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/kaiwa#8]
The file [`clientapp/templates.js`](https://github.com/ForNeVeR/kaiwa/blob/cb85afb4d16fa02f54040d39937193a880f93fee/clientapp/templates.js) seems to be auto-generated. But if I delete it from the repository, Kaiwa will have problem loading on next request (and everything will be okay after a while when the file will be generated). We should fix that (generate it synchronously on request, for example).

**Comment by vitalyster** [comment]
It is regenerated automatically when isDev set to true
