### ISSUE TITLE
Unable to click anything

### ISSUE THREAD

**Issue by bangarharshit** [ForNeVeR/kaiwa#80]
Hi Guys,
   Unable to click anything sometimes. It's an issue with kaiwa and just copying it for reference. I am trying to debug to see what can be the issue.
https://github.com/digicoop/kaiwa/issues/55
https://github.com/digicoop/kaiwa/issues/48
https://github.com/digicoop/kaiwa/issues/37

**Comment by vitalyster** [comment]
Big roster with MAM-enabled account?

**Comment by bangarharshit** [comment]
No. Very small roster (2 entries) with mam not enabled.

**Comment by vitalyster** [comment]
already fixed in https://github.com/ForNeVeR/kaiwa/commit/fa33ac775fc68f5f6960ac0800c5e73aa29e2a13

**Comment by vitalyster** [comment]
If you on git master, maybe you forgot to run `npm run compile`
