### ISSUE TITLE
Avatars not working in groupchat

### ISSUE THREAD

**Issue by PaulFreund** [ForNeVeR/kaiwa#90]
I just installed the current devel version and the avatars except for my own are not shown in groupchats. They work in the buddy list and in the private chat windows.

The <img> tags of the avatars have no src attribute. Where should they be added in the code?

**Comment by vitalyster** [comment]
We have XEP-0153 (presence based), XEP-0084 (pep-based) and gravatar.com fallback support for avatars. The only(?) working method for groupchats is presence-based, but your buddies should have capable clients and servers. If you and all your buddies are using your own server, things can be done automatically on server side (mod_vcard_xupdate for ejabberd).

**Comment by PaulFreund** [comment]
Okay in that case  the fallback to gravatar does not seem to work (there is a missing image symbol instead of the "no image"-image).

I have a client (conversations for Android) in which I see some images so I thought it works but that could be the pep based images. Do you know of a similar plugin for prosody?

**Comment by vitalyster** [comment]
grepping "vcard-temp:x:update" in prosody and prosody-modules sources tree does not give any results :(

**Comment by PaulFreund** [comment]
If I understood correctly it seems that avatars are currently only displayed when a client is including them via PEP in the groupchat. That would also explain why the avatars are vanishing once a user leaves the chat (I am not sure if the client has to reload for them to vanish). 
I am not yet familiar with how MUC users work and how PEP based avatars work but I'll read into it and maybe write a prosody module to do the copy from vcard_temp:x:update. 

On the other hand I think it would be a viable alternative to use the avatar of a matching contact you get the presence from. What do you think about this?

**Comment by vitalyster** [comment]
Not sure I'm understand. We already using `vcard-temp:x:update` from presence (XEP-0153), but it need capable client or server module, what can be done else in this app?

**Comment by PaulFreund** [comment]
Thats how it looks for me at the moment:
![](http://i.snag.gy/8FAAc.jpg)
All contacts that have missing avatars in the groupchat in this image do have avatars that work in the private chat windows and in other clients even in the groupchat (Conversations) (I just don't know how).I already implemented an xmpp app but without MUC or pep based avatars (only vcard_temp) so I don't know how it should work yet.

As the buddys in my contact list have working avatars I figured we could match their jid with the ones in the MUC and just use the already available avatars.

**Comment by vitalyster** [comment]
"Stream parsing" is done in stanza.io library, kaiwa only uses stanza.io events, see https://github.com/ForNeVeR/kaiwa/blob/develop/src/js/helpers/xmppEventHandlers.js#L238
